[MSSQL-2017]
Driver          = FreeTDS
Description     = ODBC connection via FreeTDS
Trace           = Yes
Servername      = MSSQL-2017
Database        = master

[MSSQL-EXPRESS-2019]
Driver          = FreeTDS
Description     = ODBC connection via FreeTDS
Trace           = Yes
Servername      = MSSQL-EXPRESS-2019
Database        = master

# vim: ft=dosini cms=#%s
